name: golangci-lint
on:
  push:
    paths:
      - '**.go'
    tags:
      - v*
    branches:
      - master
      - development
  pull_request:
    paths:
      - '**.go'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends git build-essential debhelper devscripts fakeroot git-buildpackage dh-make dh-systemd dh-golang libcairo2-dev libgtk-3-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

          # Show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true