name: GolangCI Lint
on:
  push:
    paths:
      - '**.go'
    tags:
      - v*
    branches:
      - master
      - development
  pull_request:
    paths:
      - '**.go'
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential git-buildpackage fakeroot libcairo2-dev libgtk-3-dev git devscripts gccgo gcc libc-dev
          mkdir -p /home/runner/.config/go/
          echo "GOFLAGS=-tags=gtk_$(pkg-config --modversion gtk+-3.0 | tr -t . _ | cut -d _ -f 1-2),pango_$(pkg-config --modversion pango | tr -t . _ | cut -d _ -f 1-2),gdk_pixbuf_$(pkg-config --modversion gdk-pixbuf-2.0 | tr -t . _ | cut -d _ -f 1-2),glib_$(pkg-config --modversion glib-2.0 | tr -t . _ | cut -d _ -f 1-2)" > /home/runner/.config/go/env
          cat /home/runner/.config/go/env
      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
